# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j4primelte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
	vendor/samsung/j4primelte/proprietary/etc/firmware/ice40.bin:system/etc/firmware/ice40.bin \
	vendor/samsung/j4primelte/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
	vendor/samsung/j4primelte/proprietary/framework/com.qti.dpmframework.jar:system/framework/com.qti.dpmframework.jar \
	vendor/samsung/j4primelte/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
	vendor/samsung/j4primelte/proprietary/framework/dpmapi.jar:system/framework/dpmapi.jar \
	vendor/samsung/j4primelte/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
	vendor/samsung/j4primelte/proprietary/lib/android.hardware.soundtrigger@2.0-core.so:system/lib/android.hardware.soundtrigger@2.0-core.so \
	vendor/samsung/j4primelte/proprietary/lib/lib_SamsungVAD_v01009.so:system/lib/lib_SamsungVAD_v01009.so \
	vendor/samsung/j4primelte/proprietary/lib/lib_src_night_shot.so:system/lib/lib_src_night_shot.so \
	vendor/samsung/j4primelte/proprietary/lib/libArcSoft3DStickerEngine.arcsoft.so:system/lib/libArcSoft3DStickerEngine.arcsoft.so \
	vendor/samsung/j4primelte/proprietary/lib/libArcSoftFaceAlignment.arcsoft.so:system/lib/libArcSoftFaceAlignment.arcsoft.so \
	vendor/samsung/j4primelte/proprietary/lib/libatomcore.quram.so:system/lib/libatomcore.quram.so \
	vendor/samsung/j4primelte/proprietary/lib/libatomjpeg.quram.so:system/lib/libatomjpeg.quram.so \
	vendor/samsung/j4primelte/proprietary/lib/libaudiosaplus_sec_legacy.so:system/lib/libaudiosaplus_sec_legacy.so \
	vendor/samsung/j4primelte/proprietary/lib/libBarcode.camera.samsung.so:system/lib/libBarcode.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libBeauty_v3.camera.samsung.so:system/lib/libBeauty_v3.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libeveryday.filter.candycamera.so:system/lib/libeveryday.filter.candycamera.so \
	vendor/samsung/j4primelte/proprietary/lib/libexifa.camera.samsung.so:system/lib/libexifa.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libFacePreProcessing.camera.samsung.so:system/lib/libFacePreProcessing.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libFacePreProcessing_jni.camera.samsung.so:system/lib/libFacePreProcessing_jni.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libheifcapture.so:system/lib/libheifcapture.so \
	vendor/samsung/j4primelte/proprietary/lib/libheifcapture_jni.media.samsung.so:system/lib/libheifcapture_jni.media.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libheifcodec_jni.so:system/lib/libheifcodec_jni.so \
	vendor/samsung/j4primelte/proprietary/lib/libheifregiondec_jni.so:system/lib/libheifregiondec_jni.so \
	vendor/samsung/j4primelte/proprietary/lib/libhigh_dynamic_range.so:system/lib/libhigh_dynamic_range.so \
	vendor/samsung/j4primelte/proprietary/lib/libHpr_LocFace_mvfd_v1.0.camera.samsung.so:system/lib/libHpr_LocFace_mvfd_v1.0.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libHpr_LocLandmark_sdm_v1.0.camera.samsung.so:system/lib/libHpr_LocLandmark_sdm_v1.0.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libHpr_RecFace_dl_v1.0.camera.samsung.so:system/lib/libHpr_RecFace_dl_v1.0.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libHpr_RecGAE_cvFeature_v1.0.camera.samsung.so:system/lib/libHpr_RecGAE_cvFeature_v1.0.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libHpr_TaskFaceClustering_hierarchical_v1.0.camera.samsung.so:system/lib/libHpr_TaskFaceClustering_hierarchical_v1.0.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libHprFace_FD_api.camera.samsung.so:system/lib/libHprFace_FD_api.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libHprFace_FD_jni.camera.samsung.so:system/lib/libHprFace_FD_jni.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libHprFace_GAE_api.camera.samsung.so:system/lib/libHprFace_GAE_api.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libHprFace_GAE_jni.camera.samsung.so:system/lib/libHprFace_GAE_jni.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libHprFace_LD_api.camera.samsung.so:system/lib/libHprFace_LD_api.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libHprFace_LD_jni.camera.samsung.so:system/lib/libHprFace_LD_jni.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libHprFace_utils_api.camera.samsung.so:system/lib/libHprFace_utils_api.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libHprFace_utils_jni.camera.samsung.so:system/lib/libHprFace_utils_jni.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libImageScreener.camera.samsung.so:system/lib/libImageScreener.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libImageSequenceStabilizer.camera.samsung.so:system/lib/libImageSequenceStabilizer.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libInteractivePanoramaUtil.so:system/lib/libInteractivePanoramaUtil.so \
	vendor/samsung/j4primelte/proprietary/lib/libInteractiveSegmentation.camera.samsung.so:system/lib/libInteractiveSegmentation.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libjpega.camera.samsung.so:system/lib/libjpega.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libjpegsq.media.samsung.so:system/lib/libjpegsq.media.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libknox_keyutils.so:system/lib/libknox_keyutils.so \
	vendor/samsung/j4primelte/proprietary/lib/libmaple.filter.thundersoft.so:system/lib/libmaple.filter.thundersoft.so \
	vendor/samsung/j4primelte/proprietary/lib/libMattingCore.camera.samsung.so:system/lib/libMattingCore.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libMLDAP.so:system/lib/libMLDAP.so \
	vendor/samsung/j4primelte/proprietary/lib/libmldapchecker.so:system/lib/libmldapchecker.so \
	vendor/samsung/j4primelte/proprietary/lib/libsaiv_HprFace_api.camera.samsung.so:system/lib/libsaiv_HprFace_api.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libsaiv_HprFace_cmh_support_jni.camera.samsung.so:system/lib/libsaiv_HprFace_cmh_support_jni.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/libsamsungvad.so:system/lib/libsamsungvad.so \
	vendor/samsung/j4primelte/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
	vendor/samsung/j4primelte/proprietary/lib/libsemcamera_jni.camera.samsung.so:system/lib/libsemcamera_jni.camera.samsung.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.gnss@1.0.so:system/lib/vendor.qti.gnss@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.gnss@1.1.so:system/lib/vendor.qti.gnss@1.1.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.gnss@1.2.so:system/lib/vendor.qti.gnss@1.2.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.gnss@2.0.so:system/lib/vendor.qti.gnss@2.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.gnss@2.1.so:system/lib/vendor.qti.gnss@2.1.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.hardware.automotive.vehicle@1.0.so:system/lib/vendor.qti.hardware.automotive.vehicle@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.hardware.camera.device@1.0.so:system/lib/vendor.qti.hardware.camera.device@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.hardware.data.latency@1.0.so:system/lib/vendor.qti.hardware.data.latency@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.hardware.fm@1.0.so:system/lib/vendor.qti.hardware.fm@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.hardware.iop@1.0.so:system/lib/vendor.qti.hardware.iop@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.hardware.iop@2.0.so:system/lib/vendor.qti.hardware.iop@2.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.hardware.perf@1.0.so:system/lib/vendor.qti.hardware.perf@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.hardware.qdutils_disp@1.0.so:system/lib/vendor.qti.hardware.qdutils_disp@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.hardware.radio.atcmdfwd@1.0.so:system/lib/vendor.qti.hardware.radio.atcmdfwd@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.hardware.tui_comm@1.0.so:system/lib/vendor.qti.hardware.tui_comm@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.hardware.vpp@1.1.so:system/lib/vendor.qti.hardware.vpp@1.1.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.qti.voiceprint@1.0.so:system/lib/vendor.qti.voiceprint@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.external.secure_storage@2.0.so:system/lib/vendor.samsung.external.secure_storage@2.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.hardware.bluetooth@1.0.so:system/lib/vendor.samsung.hardware.bluetooth@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.hardware.camera.device@1.0.so:system/lib/vendor.samsung.hardware.camera.device@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.hardware.camera.device@3.2.so:system/lib/vendor.samsung.hardware.camera.device@3.2.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.hardware.camera.device@3.3.so:system/lib/vendor.samsung.hardware.camera.device@3.3.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.hardware.camera.device@3.4.so:system/lib/vendor.samsung.hardware.camera.device@3.4.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.hardware.camera.provider@2.4.so:system/lib/vendor.samsung.hardware.camera.provider@2.4.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.hardware.camera.provider@2.5.so:system/lib/vendor.samsung.hardware.camera.provider@2.5.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.hardware.exthealth@1.0.so:system/lib/vendor.samsung.hardware.exthealth@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.hardware.gnss@1.0.so:system/lib/vendor.samsung.hardware.gnss@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.hardware.light@2.0.so:system/lib/vendor.samsung.hardware.light@2.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.hardware.miscpower@1.0.so:system/lib/vendor.samsung.hardware.miscpower@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.hardware.radio.secbridge@1.0.so:system/lib/vendor.samsung.hardware.radio.secbridge@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.hardware.vibrator@1.0.so:system/lib/vendor.samsung.hardware.vibrator@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.hardware.wifi.hostapd@1.0.so:system/lib/vendor.samsung.hardware.wifi.hostapd@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.hardware.wifi.supplicant@1.0.so:system/lib/vendor.samsung.hardware.wifi.supplicant@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.hardware.wifi@1.0.so:system/lib/vendor.samsung.hardware.wifi@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.security.sem@1.0.so:system/lib/vendor.samsung.security.sem@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.security.skpm@1.0.so:system/lib/vendor.samsung.security.skpm@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.samsung.security.wvkprov_server@1.0.so:system/lib/vendor.samsung.security.wvkprov_server@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.trustonic.tee@1.0.so:system/lib/vendor.trustonic.tee@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/vendor.trustonic.teeregistry@1.0.so:system/lib/vendor.trustonic.teeregistry@1.0.so \
	vendor/samsung/j4primelte/proprietary/lib/hw/audio.tms.default.so:system/lib/hw/audio.tms.default.so \
	vendor/samsung/j4primelte/proprietary/lib/hw/face.default.so:system/lib/hw/face.default.so
